In [1]:
import tensorflow as tf
import pandas as pd
import numpy as np
import tflearn

/usr/local/Cellar/python/3.6.4_4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
  return f(*args, **kwds)


hdf5 is not supported on this machine (please install/reinstall h5py for optimal experience)
Scipy not supported!


In [2]:
df=pd.read_csv('surfData/surfData.csv',index_col=0)
#print(df)

In [3]:
a=[]
for i in range(860):
    a.append([df.iat[i,18]])
print(a)

[[1806], [1907], [605], [1807], [1807], [1806], [1806], [1806], [1904], [504], [1707], [1804], [1813], [1706], [1904], [1706], [202], [1806], [1707], [504], [1707], [1804], [1813], [1706], [1904], [1706], [202], [1806], [1707], [1707], [504], [1707], [1804], [1813], [1706], [1904], [202], [1806], [1707], [1904], [1709], [1707], [1707], [1813], [1707], [504], [1804], [1813], [1706], [1707], [1805], [1904], [1709], [1707], [1707], [1813], [504], [1804], [1706], [1707], [1709], [1906], [1707], [1805], [1707], [1813], [504], [1804], [1706], [403], [403], [605], [1906], [1708], [1707], [1709], [1906], [1707], [1805], [1707], [403], [403], [605], [1906], [1708], [1707], [1709], [1906], [1805], [1707], [1707], [403], [403], [605], [1906], [1708], [1709], [1906], [1805], [1906], [1905], [1707], [1708], [1906], [1807], [1707], [403], [403], [605], [605], [306], [1706], [1906], [1905], [1707], [1708], [1906], [1807], [1707], [1707], [605], [306], [1706], [1906], [1905], [1708], [1906], [1807], [

In [4]:
arr=np.array(a)
aTest=[]
for i in range(860):
    if arr[i] >= 1000:
        aTest.append([1,0])
    else:
        aTest.append([0,1])
trainY=np.array(aTest)
print(trainY)

[[1 0]
 [1 0]
 [0 1]
 ..., 
 [0 1]
 [0 1]
 [0 1]]


In [5]:
b=[]
for i in range(860):
    b.append([df.iat[i,9],df.iat[i,11],df.iat[i,13],df.iat[i,15],df.iat[i,23]])
trainX=np.array(b)
print(trainX)
#9,weather id
#11,wind direction id
#13,wind strength id
#15,wind type id
#17,wave size id
#23,wave condition id
#31,surface temperature
#32,surface temperature difference

[[ 2  6  4  4 17]
 [ 2  4  4  1 17]
 [ 2  6  4  1 17]
 ..., 
 [11  1  1  5 16]
 [11  1  1  2 18]
 [ 4  1  2  5 17]]


In [6]:
c=[]
for i in range(860,870):
    c.append([df.iat[i,18]])
cArr=np.array(c)
cTest=[]
for i in range(10):
    if cArr[i]>=1000:
        cTest.append([1,0])
    else:
        cTest.append([0,1])
testY=np.array(cTest);
print(testY);

[[1 0]
 [1 0]
 [0 1]
 [1 0]
 [1 0]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]]


In [7]:
d=[]
for i in range(860,870):
    d.append([df.iat[i,9],df.iat[i,11],df.iat[i,13],df.iat[i,15],df.iat[i,23]])
testX=np.array(d)
print(testX)

[[10  2  2  3 15]
 [11  1  1  3 15]
 [11  2  1  1 16]
 [11  2  1  4 15]
 [11  1  1  5 15]
 [11  1  1  2 17]
 [11  1  1  2 18]
 [11  1  1  5 16]
 [11  1  1  2 18]
 [ 4  1  2  5 17]]


In [8]:
tf.reset_default_graph()
tnorm = tflearn.initializations.uniform(minval=-1.0, maxval=1.0)
net=tflearn.input_data(shape=[None,5])
net=tflearn.fully_connected(net,5,activation='sigmoid')
net=tflearn.fully_connected(net,5,activation='sigmoid')
#net=tflearn.fully_connected(net,4,activation='sigmoid')
net = tflearn.fully_connected(net,2,activation='softmax')
net = tflearn.regression(net,optimizer='sgd',learning_rate=0.5,loss='mean_square')

In [9]:
model = tflearn.DNN(net) 
model.fit(trainX,trainY,n_epoch=1000,batch_size=16,validation_set=0.1,show_metric=True)

Training Step: 48999  | total loss: 0.12113 | time: 0.161s
| SGD | epoch: 1000 | loss: 0.12113 - acc: 0.8569 -- iter: 768/774
Training Step: 49000  | total loss: 0.14190 | time: 1.170s
| SGD | epoch: 1000 | loss: 0.14190 - acc: 0.7891 | val_loss: 0.19296 - val_acc: 0.7326 -- iter: 774/774
--


In [10]:
pred = np.array(model.predict(testX))
print(pred)

label = testY
print(label)

[[ 0.6114651   0.38853487]
 [ 0.58443218  0.41556785]
 [ 0.04329972  0.95670027]
 [ 0.96032971  0.03967028]
 [ 0.81219614  0.1878038 ]
 [ 0.06721342  0.93278652]
 [ 0.08282244  0.91717756]
 [ 0.62441152  0.37558848]
 [ 0.08282244  0.91717756]
 [ 0.61795533  0.38204458]]
[[1 0]
 [1 0]
 [0 1]
 [1 0]
 [1 0]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]]
