In [1]:
import tensorflow as tf
import pandas as pd
import numpy as np
import tflearn

/usr/local/Cellar/python/3.6.4_4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
  return f(*args, **kwds)


hdf5 is not supported on this machine (please install/reinstall h5py for optimal experience)
Scipy not supported!


In [2]:
df=pd.read_csv('surfData/surfData.csv',index_col=0)
print(df)

          nami_point_id  region_id  area_id  pinpoint_id  max_update_idx  \
point_id                                                                   
1160015            1215          5      401         1740            6267   
1160016            1216          5      401         1741            4457   
1160006            1206          5      401         1685            4384   
1160021            1221          5      401         1750            4469   
1160025            1225          5      401         1756            4462   
1160001            1201          5      401         1675            3629   
1160028            1228          5      401         1766            4531   
1160096            1297          5      401         8591            3635   
1160004            1204          5      401         1679            3630   
1160006            1206          5      401         1685            4385   
1160021            1221          5      401         1750            4470   
1160001     

In [3]:
a=[]
for i in range(350):
    a.append([df.iat[i,18]])
print(a)

[[1806], [1907], [605], [1807], [1807], [1806], [1806], [1806], [1904], [504], [1707], [1804], [1813], [1706], [1904], [1706], [202], [1806], [1707], [504], [1707], [1804], [1813], [1706], [1904], [1706], [202], [1806], [1707], [1707], [504], [1707], [1804], [1813], [1706], [1904], [202], [1806], [1707], [1904], [1709], [1707], [1707], [1813], [1707], [504], [1804], [1813], [1706], [1707], [1805], [1904], [1709], [1707], [1707], [1813], [504], [1804], [1706], [1707], [1709], [1906], [1707], [1805], [1707], [1813], [504], [1804], [1706], [403], [403], [605], [1906], [1708], [1707], [1709], [1906], [1707], [1805], [1707], [403], [403], [605], [1906], [1708], [1707], [1709], [1906], [1805], [1707], [1707], [403], [403], [605], [1906], [1708], [1709], [1906], [1805], [1906], [1905], [1707], [1708], [1906], [1807], [1707], [403], [403], [605], [605], [306], [1706], [1906], [1905], [1707], [1708], [1906], [1807], [1707], [1707], [605], [306], [1706], [1906], [1905], [1708], [1906], [1807], [

In [4]:
arr=np.array(a)
aTest=[]
for i in range(350):
    if arr[i] >= 1000:
        aTest.append([1,0])
    else:
        aTest.append([0,1])
trainY=np.array(aTest)
print(trainY)

[[1 0]
 [1 0]
 [0 1]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [0 1]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [0 1]
 [1 0]
 [1 0]
 [0 1]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [0 1]
 [1 0]
 [1 0]
 [1 0]
 [0 1]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [0 1]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [0 1]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [0 1]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [0 1]
 [1 0]
 [1 0]
 [0 1]
 [0 1]
 [0 1]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [0 1]
 [0 1]
 [0 1]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [0 1]
 [0 1]
 [0 1]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [0 1]
 [0 1]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [0 1]
 [1 0]
 [0 1]
 [0 1]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [0 1]

In [5]:
b=[]
for i in range(350):
    b.append([df.iat[i,9],df.iat[i,11],df.iat[i,13],df.iat[i,15],df.iat[i,31]])
trainX=np.array(b)
print(trainX)

[[  2.    6.    4.    4.   23.5]
 [  2.    4.    4.    1.   23.9]
 [  2.    6.    4.    1.   23.9]
 ..., 
 [  2.    2.    3.    5.   25.2]
 [  2.    2.    3.    5.   25.2]
 [  2.    3.    3.    3.   24.9]]


In [6]:
c=[]
for i in range(350,360):
    c.append([df.iat[i,18]])
cArr=np.array(c)
cTest=[]
for i in range(10):
    if cArr[i]>=1000:
        cTest.append([1,0])
    else:
        cTest.append([0,1])
testY=np.array(cTest);
print(testY);

[[0 1]
 [1 0]
 [1 0]
 [1 0]
 [0 1]
 [1 0]
 [1 0]
 [1 0]
 [0 1]
 [1 0]]


In [7]:
d=[]
for i in range(350,360):
    d.append([df.iat[i,9],df.iat[i,11],df.iat[i,13],df.iat[i,15],df.iat[i,31]])
testX=np.array(d)
print(testX)

[[  2.    4.    0.    4.   24.9]
 [  2.    3.    0.    5.   25. ]
 [  2.    3.    2.    1.   24.7]
 [  2.    3.    0.    4.   25. ]
 [  2.    3.    2.    1.   24.6]
 [  2.    3.    2.    4.   25. ]
 [  2.    3.    3.    4.   25. ]
 [  2.    2.    3.    5.   25.2]
 [  2.    2.    3.    5.   25.2]
 [  2.    3.    3.    3.   24.9]]


In [8]:
tf.reset_default_graph()
net=tflearn.input_data(shape=[None,5])
net=tflearn.fully_connected(net,4,activation='relu')
#net=tflearn.fully_connected(net,4,activation='relu')
#net=tflearn.fully_connected(net,4,activation='relu')
net = tflearn.fully_connected(net,2,activation='softmax')
net = tflearn.regression(net,optimizer='sgd',learning_rate=0.5,loss='categorical_crossentropy')

In [9]:
model = tflearn.DNN(net) 
model.fit(trainX,trainY,n_epoch=20,batch_size=2,validation_set=0.1,show_metric=True)

Training Step: 3159  | total loss: 0.56622 | time: 0.636s
| SGD | epoch: 020 | loss: 0.56622 - acc: 0.7232 -- iter: 314/315
Training Step: 3160  | total loss: 0.52607 | time: 1.648s
| SGD | epoch: 020 | loss: 0.52607 - acc: 0.7509 | val_loss: 0.64196 - val_acc: 0.7429 -- iter: 315/315
--


In [10]:
pred = np.array(model.predict(testX))
print(pred)

label = testY
print(label)

[[ 0.88136554  0.11863452]
 [ 0.88136554  0.11863452]
 [ 0.88136554  0.11863452]
 [ 0.88136554  0.11863452]
 [ 0.88136554  0.11863452]
 [ 0.88136554  0.11863452]
 [ 0.88136554  0.11863452]
 [ 0.88136554  0.11863452]
 [ 0.88136554  0.11863452]
 [ 0.88136554  0.11863452]]
[[0 1]
 [1 0]
 [1 0]
 [1 0]
 [0 1]
 [1 0]
 [1 0]
 [1 0]
 [0 1]
 [1 0]]
