In [1]:
import tensorflow as tf
import pandas as pd
import numpy as np
import tflearn

/usr/local/Cellar/python/3.6.4_4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
  return f(*args, **kwds)


hdf5 is not supported on this machine (please install/reinstall h5py for optimal experience)
Scipy not supported!


In [2]:
df=pd.read_csv('surfData/surfData.csv',index_col=0)
#print(df)

In [3]:
a=[]
for i in range(630):
    a.append([df.iat[i,18]])
print(a)

[[1806], [1907], [605], [1807], [1807], [1806], [1806], [1806], [1904], [504], [1707], [1804], [1813], [1706], [1904], [1706], [202], [1806], [1707], [504], [1707], [1804], [1813], [1706], [1904], [1706], [202], [1806], [1707], [1707], [504], [1707], [1804], [1813], [1706], [1904], [202], [1806], [1707], [1904], [1709], [1707], [1707], [1813], [1707], [504], [1804], [1813], [1706], [1707], [1805], [1904], [1709], [1707], [1707], [1813], [504], [1804], [1706], [1707], [1709], [1906], [1707], [1805], [1707], [1813], [504], [1804], [1706], [403], [403], [605], [1906], [1708], [1707], [1709], [1906], [1707], [1805], [1707], [403], [403], [605], [1906], [1708], [1707], [1709], [1906], [1805], [1707], [1707], [403], [403], [605], [1906], [1708], [1709], [1906], [1805], [1906], [1905], [1707], [1708], [1906], [1807], [1707], [403], [403], [605], [605], [306], [1706], [1906], [1905], [1707], [1708], [1906], [1807], [1707], [1707], [605], [306], [1706], [1906], [1905], [1708], [1906], [1807], [

In [4]:
arr=np.array(a)
aTest=[]
for i in range(630):
    if arr[i] >= 1000:
        aTest.append([1,0])
    else:
        aTest.append([0,1])
trainY=np.array(aTest)
print(trainY)

[[1 0]
 [1 0]
 [0 1]
 ..., 
 [1 0]
 [1 0]
 [1 0]]


In [5]:
b=[]
for i in range(630):
    b.append([df.iat[i,9],df.iat[i,11],df.iat[i,13],df.iat[i,15],df.iat[i,17]])
trainX=np.array(b)
print(trainX)
#9,weather id
#11,wind direction id
#13,wind strength id
#15,wind type id
#17,wave size id
#31,surface temperature

[[ 2  6  4  4 18]
 [ 2  4  4  1 19]
 [ 2  6  4  1  6]
 ..., 
 [ 4  1  3  5 21]
 [ 5  1  3  5 22]
 [ 4  2  3  2 20]]


In [6]:
c=[]
for i in range(630,640):
    c.append([df.iat[i,18]])
cArr=np.array(c)
cTest=[]
for i in range(10):
    if cArr[i]>=1000:
        cTest.append([1,0])
    else:
        cTest.append([0,1])
testY=np.array(cTest);
print(testY);

[[1 0]
 [1 0]
 [1 0]
 [1 0]
 [0 1]
 [0 1]
 [1 0]
 [1 0]
 [1 0]
 [1 0]]


In [7]:
d=[]
for i in range(630,640):
    d.append([df.iat[i,9],df.iat[i,11],df.iat[i,13],df.iat[i,15],df.iat[i,17]])
testX=np.array(d)
print(testX)

[[ 4  2  2  1 21]
 [ 4  2  3  3 10]
 [ 4  2  2  4 24]
 [ 4  2  2  4 22]
 [ 4  2  3  5  6]
 [ 4  2  3  5  6]
 [ 4  2  3  3 23]
 [ 4  1  3  5 21]
 [ 5  1  3  5 22]
 [ 4  2  3  2 20]]


In [8]:
tf.reset_default_graph()
tnorm = tflearn.initializations.uniform(minval=-1.0, maxval=1.0)
net=tflearn.input_data(shape=[None,5])
net=tflearn.fully_connected(net,4,activation='sigmoid')
net=tflearn.fully_connected(net,4,activation='sigmoid')
#net=tflearn.fully_connected(net,2,activation='sigmoid')
net = tflearn.fully_connected(net,2,activation='sigmoid')
net = tflearn.regression(net,optimizer='sgd',learning_rate=0.5,loss='mean_square')

In [9]:
model = tflearn.DNN(net) 
model.fit(trainX,trainY,n_epoch=350,batch_size=256,validation_set=0.1,show_metric=True)

Training Step: 1049  | total loss: 0.03834 | time: 0.005s
| SGD | epoch: 350 | loss: 0.03834 - acc: 0.9654 -- iter: 512/567
Training Step: 1050  | total loss: 0.03673 | time: 1.019s
| SGD | epoch: 350 | loss: 0.03673 - acc: 0.9677 | val_loss: 0.03731 - val_acc: 0.9683 -- iter: 567/567
--


In [10]:
pred = np.array(model.predict(testX))
print(pred)

label = testY
print(label)

[[ 0.94062692  0.05944144]
 [ 0.22447266  0.775316  ]
 [ 0.94053847  0.05952991]
 [ 0.94005954  0.0600093 ]
 [ 0.14609061  0.85374707]
 [ 0.14609061  0.85374707]
 [ 0.94051832  0.05955004]
 [ 0.93721527  0.06285574]
 [ 0.93673277  0.06333862]
 [ 0.94012475  0.05994405]]
[[1 0]
 [1 0]
 [1 0]
 [1 0]
 [0 1]
 [0 1]
 [1 0]
 [1 0]
 [1 0]
 [1 0]]
